const FEATURED = [
  {
    id: 1,
    title: 'Featured post',
    date: '12/05/2018',
    adress: 'rue liberté tunis 1000',
    img: 'http://aeroengineer.org/wp-content/uploads/2016/11/NASA.png',
    description: 'This is a wider card with supporting text below as a natural lead-in to additional content.',
    company: 'imagine partners',
    hashtags: ['react', 'node'],
    price: 2,
  },
  {
    id: 2,
    title: 'Post title',
    date: 'Nov 11',
    adress: 'rue liberté tunis 1000',
    img: 'http://aeroengineer.org/wp-content/uploads/2016/11/NASA.png',
    description: 'http://aeroengineer.org/wp-content/uploads/2016/11/NASA.png',
    company: 'imagine partners',
    hashtags: ['react', 'node'],
    price: 3,
  },
  {
    id: 3,
    title: 'HAJRIAYMEN',
    date: 'Nov 11',
    adress: 'rue liberté tunis 1000',
    img: 'http://aeroengineer.org/wp-content/uploads/2016/11/NASA.png',
    description: 'http://aeroengineer.org/wp-content/uploads/2016/11/NASA.png',
    company: 'imagine partners',
    hashtags: ['react', 'node'],
  },
  {
    id: 4,
    title: 'adel',
    date: 'Nov 11',
    adress: 'rue liberté tunis 1000',
    img: 'http://aeroengineer.org/wp-content/uploads/2016/11/NASA.png',
    description: 'http://aeroengineer.org/wp-content/uploads/2016/11/NASA.png',
    company: 'imagine partners',
    hashtags: ['react', 'node'],
    price: 4,
  },
  {
    id: 5,
    title: 'soulee',
    date: 'Nov 11',
    adress: 'rue liberté tunis 1000',
    img: 'http://aeroengineer.org/wp-content/uploads/2016/11/NASA.png',
    description: 'http://aeroengineer.org/wp-content/uploads/2016/11/NASA.png',
    company: 'imagine partners',
    hashtags: ['react', 'node'],
    price: 5,
  },
  {
    id: 6,
    title: 'slim',
    date: 'Nov 11',
    adress: 'rue liberté tunis 1000',
    img: 'http://aeroengineer.org/wp-content/uploads/2016/11/NASA.png',
    description: 'http://aeroengineer.org/wp-content/uploads/2016/11/NASA.png',
    company: 'imagine partners',
    hashtags: ['react', 'node'],
    price: 6,
  },
  {
    id: 7,
    title: 'qsdqs',
    date: 'Nov 11',
    adress: 'rue liberté tunis 1000',
    img: 'http://aeroengineer.org/wp-content/uploads/2016/11/NASA.png',
    description: 'http://aeroengineer.org/wp-content/uploads/2016/11/NASA.png',
    company: 'imagine partners',
    hashtags: ['react', 'node'],
    price: 7,
  },
];
export default FEATURED;
